"""Composable 2D mechanics assets (Milestone 1).

See plans/physics_asset_library.md. Public API is curated here so scenes import
from ``physics_through_anim.physics.mechanics``.
"""

from physics_through_anim.physics.mechanics.assembly import Assembly, Relation
from physics_through_anim.physics.mechanics.base import ForceSpec, PhysicsAsset, Ref
from physics_through_anim.physics.mechanics.bodies import Block, Particle, RectangularMass
from physics_through_anim.physics.mechanics.chain import (
    Chain,
    ChainRender,
    ChainShapeState,
    DistributedBody,
    ElasticString,
    FlexibleRod,
    MassiveSpring,
)
from physics_through_anim.physics.mechanics.circular import (
    CircularBody,
    Cylinder,
    Disk,
    Hoop,
    MountedPulley,
    Pulley,
    PulleyBracket,
    PulleyMount,
    Ring,
    Sphere2D,
    mount_pulley,
)
from physics_through_anim.physics.mechanics.connectors import (
    Cable,
    Connector,
    Hinge,
    MasslessLink,
    PinJoint,
    Rope,
    RopeOverPulley,
    SlackString,
)
from physics_through_anim.physics.mechanics.constraints import (
    ContactLockConstraint,
    DistanceConstraint,
    FixedAxleConstraint,
    FixedPointConstraint,
    PathConstraint,
    PinConstraint,
    RollingConstraint,
    RopeLengthConstraint,
    SlotConstraint,
)
from physics_through_anim.physics.mechanics.contact import (
    Contact,
    ContactGeometry,
    ContactKinematics,
    ContactLifecycle,
    FrictionModel,
    MaterialPairing,
)
from physics_through_anim.physics.mechanics.environment import Ceiling, Conveyor, Corner, Incline
from physics_through_anim.physics.mechanics.geometry import (
    Circle2D,
    Polygon2D,
    clearance,
    contact_state,
    corner_seat,
    no_penetration_clamp,
    signed_distance,
)
from physics_through_anim.physics.mechanics.kinds import (
    Bearing,
    BodyDynamics,
    ContactPersistence,
    ContactRegime,
    ForceKind,
    Keypoint,
    MotionState,
    Phase,
    RelationKind,
)
from physics_through_anim.physics.mechanics.orbital import (
    CentralBody,
    KeplerEllipseTrajectory,
    OrbitPath,
    away_from,
    focus_marker,
    toward,
)
from physics_through_anim.physics.mechanics.rod import Rod
from physics_through_anim.physics.mechanics.springs import (
    Damper,
    HookeLaw,
    LinearDamperLaw,
    LinearSpring,
    Spring,
    SpringGroup,
    TorsionalHookeLaw,
    TorsionSpring,
    parallel_springs,
    series_springs,
)
from physics_through_anim.physics.mechanics.supports import Floor, Support, Wall
from physics_through_anim.physics.mechanics.surfaces import (
    FloorSurface,
    InclineSurface,
    LineSurface,
)
from physics_through_anim.physics.mechanics.surfaces_curved import (
    CircularTrack,
    ConcaveSurface,
    ConvexSurface,
    ParametricSurface,
    Peg,
    Rail,
    RoundedEdge,
    SharpEdge,
    Slot,
    Table,
    separation_imminent,
)

__all__ = [
    "Assembly",
    "Block",
    "BodyDynamics",
    "Bearing",
    "Cable",
    "Ceiling",
    "CentralBody",
    "Chain",
    "ChainRender",
    "ChainShapeState",
    "Circle2D",
    "CircularBody",
    "CircularTrack",
    "ConcaveSurface",
    "Connector",
    "ConvexSurface",
    "Contact",
    "ContactGeometry",
    "ContactKinematics",
    "ContactLifecycle",
    "ContactLockConstraint",
    "ContactPersistence",
    "ContactRegime",
    "Conveyor",
    "Corner",
    "Cylinder",
    "Damper",
    "Disk",
    "DistributedBody",
    "DistanceConstraint",
    "ElasticString",
    "FixedAxleConstraint",
    "FixedPointConstraint",
    "Floor",
    "FloorSurface",
    "FlexibleRod",
    "ForceKind",
    "ForceSpec",
    "FrictionModel",
    "Hinge",
    "Hoop",
    "HookeLaw",
    "Incline",
    "InclineSurface",
    "KeplerEllipseTrajectory",
    "Keypoint",
    "LineSurface",
    "LinearDamperLaw",
    "LinearSpring",
    "MasslessLink",
    "MaterialPairing",
    "MassiveSpring",
    "MotionState",
    "MountedPulley",
    "OrbitPath",
    "ParametricSurface",
    "Particle",
    "PathConstraint",
    "Peg",
    "Phase",
    "PhysicsAsset",
    "PinConstraint",
    "PinJoint",
    "Polygon2D",
    "Pulley",
    "PulleyBracket",
    "PulleyMount",
    "Rail",
    "RectangularMass",
    "Ref",
    "Relation",
    "RelationKind",
    "Ring",
    "Rod",
    "RollingConstraint",
    "Rope",
    "RopeLengthConstraint",
    "RopeOverPulley",
    "RoundedEdge",
    "SharpEdge",
    "SlackString",
    "Slot",
    "SlotConstraint",
    "Sphere2D",
    "Spring",
    "SpringGroup",
    "Support",
    "Table",
    "TorsionSpring",
    "TorsionalHookeLaw",
    "Wall",
    "clearance",
    "contact_state",
    "corner_seat",
    "away_from",
    "focus_marker",
    "mount_pulley",
    "no_penetration_clamp",
    "parallel_springs",
    "separation_imminent",
    "series_springs",
    "signed_distance",
    "toward",
]
